-- Seed Knowledge Base with Platform Features and FAQs
-- Comprehensive feature database for One2One Love platform

-- 💕 Connection Building Features
INSERT INTO chatbot_knowledge (content_type, title, content, metadata) VALUES
('feature', 'Love Notes', 'Send personalized love notes to your partner through the app, SMS, or social media. Basis: 50+ notes, Premiere: 1000+ notes, Exclusive: Unlimited. You can schedule surprise messages and use AI Content Creator (Exclusive) to generate custom notes.', '{"language": "en", "subscription_tier": "all", "tags": ["communication", "connection", "love-notes"]}'),
('feature', 'Scheduled Love Notes', 'Plan surprise messages in advance. Schedule love notes to be sent at specific times to surprise your partner. Available in Premiere and Exclusive tiers.', '{"language": "en", "subscription_tier": "premium", "tags": ["communication", "surprise", "scheduling"]}'),
('feature', 'AI Content Creator', 'Generate personalized content including love notes, poems, letters, and conversation starters. Uses AI to create unique, heartfelt messages. Available exclusively in Exclusive tier ($34.99/month).', '{"language": "en", "subscription_tier": "exclusive", "tags": ["content", "personalization", "ai", "poems"]}'),
('feature', 'Date Ideas', 'Discover curated date ideas filtered by budget, location, and occasion. Basis: 5 ideas/month, Premiere/Exclusive: Unlimited. Create custom date ideas or browse suggestions to keep the spark alive.', '{"language": "en", "subscription_tier": "all", "tags": ["activities", "connection", "dates", "romance"]}'),
('feature', 'Memory Lane', 'Capture and cherish special moments with photos and notes. Build a beautiful digital timeline of your relationship journey together. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["memories", "connection", "photos", "timeline"]}'),
('feature', 'Shared Journals', 'Write together and document your relationship journey. Create shared journal entries that both partners can contribute to. Perfect for reflecting on your relationship growth.', '{"language": "en", "subscription_tier": "all", "tags": ["memories", "writing", "reflection"]}'),
('feature', 'Cooperative Games', 'Fun games designed for couples to play together. Strengthen your bond through playful activities and shared experiences. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["activities", "games", "fun", "connection"]}'),
('feature', 'Couples Calendar', 'Shared calendar for events, dates, and important occasions. Sync your schedules and never miss an important moment together. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["planning", "organization", "events"]}'),

-- 🎯 Relationship Growth Features
('feature', 'Relationship Goals', 'Set and track relationship goals with actionable steps. Monitor your progress together and celebrate achievements. Available in Premiere and Exclusive tiers. Goals help couples grow and strengthen their bond.', '{"language": "en", "subscription_tier": "premium", "tags": ["growth", "planning", "goals", "tracking"]}'),
('feature', 'Milestones', 'Track important relationship dates and anniversaries. Get reminders and celebration suggestions for your special moments together. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["memories", "celebration", "anniversaries", "dates"]}'),
('feature', 'Love Language Quiz', 'Discover your and your partner''s love languages. Understand how you both give and receive love to improve your connection. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["discovery", "quiz", "love-languages", "compatibility"]}'),
('feature', 'Relationship Quizzes', 'Take insightful quizzes together to discover more about each other, communication styles, and relationship dynamics. Basis: Basic quizzes, Premiere/Exclusive: Advanced quizzes and compatibility tests.', '{"language": "en", "subscription_tier": "all", "tags": ["discovery", "fun", "quiz", "compatibility"]}'),
('feature', 'Couples Dashboard', 'Overview of your relationship health and progress. Visualize your journey together with insights and statistics. Available in Premiere and Exclusive tiers.', '{"language": "en", "subscription_tier": "premium", "tags": ["analytics", "insights", "dashboard", "progress"]}'),
('feature', 'Progress Tracking', 'Visualize relationship growth over time. Track improvements in communication, connection, and goal achievement. Available in Premiere and Exclusive tiers.', '{"language": "en", "subscription_tier": "premium", "tags": ["analytics", "growth", "tracking", "visualization"]}'),

-- 💬 Communication & Support Features
('feature', 'AI Relationship Coach', 'Get personalized relationship advice and daily tips from our AI coach. Basis: Not available, Premiere: 50 questions/month, Exclusive: Unlimited. Get 24/7 relationship support and guidance.', '{"language": "en", "subscription_tier": "premium", "tags": ["advice", "support", "ai", "coaching"]}'),
('feature', 'Communication Practice', 'Practice healthy communication through interactive scenarios. Learn effective communication techniques and resolve conflicts constructively. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["communication", "conflict", "practice", "scenarios"]}'),
('feature', 'Meditation', 'Guided meditation sessions designed for couples to practice mindfulness together and reduce stress in your relationship. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["wellness", "relaxation", "mindfulness", "stress-relief"]}'),
('feature', 'Counseling Support', 'Connect with licensed therapists and relationship counselors through the platform. Get professional help when you need it. Available in all tiers with different access levels.', '{"language": "en", "subscription_tier": "all", "tags": ["support", "professional", "therapy", "counseling"]}'),
('feature', 'Podcasts', 'Access relationship podcasts and expert advice. Listen to insights from relationship experts, therapists, and influencers. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["content", "learning", "expert-advice", "audio"]}'),
('feature', 'Articles', 'Read educational content and guides on relationships, communication, intimacy, and more. Expert-written articles to help you grow together. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["content", "learning", "education", "guides"]}'),
('feature', 'Influencers', 'Follow relationship experts and influencers on the platform. Get daily tips, insights, and inspiration from trusted relationship coaches. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["content", "experts", "influencers", "inspiration"]}'),
('feature', 'Chat System', 'Real-time messaging system between couples. Private chat to communicate with your partner within the app. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["communication", "messaging", "real-time"]}'),

-- 👥 Community & Social Features
('feature', 'Community', 'Join user-created communities and forums. Connect with other couples, share experiences, and participate in discussions. Available in all tiers, with Exclusive Community access in Exclusive tier.', '{"language": "en", "subscription_tier": "all", "tags": ["social", "connection", "forums", "communities"]}'),
('feature', 'Find Friends', 'Connect with other couples on the platform. Find couples with similar interests, relationship stages, or goals. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["social", "connection", "friends", "networking"]}'),
('feature', 'Buddy System', 'Match with compatible couples through our buddy system. Find couple friends who share your values and relationship goals. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["social", "matching", "friends", "compatibility"]}'),
('feature', 'Success Stories', 'Share and read relationship success stories from other couples. Get inspired by real couples who have strengthened their relationships. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["social", "inspiration", "stories", "community"]}'),
('feature', 'Leaderboard', 'Compete with other couples on weekly, monthly, and yearly leaderboards. Earn points through activities and see how you rank. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["gamification", "competition", "leaderboard", "ranking"]}'),
('feature', 'Win a Cruise', 'Enter monthly and yearly contests to win amazing prizes including cruises. Exclusive tier gets automatic contest entry. Available in all tiers with different entry methods.', '{"language": "en", "subscription_tier": "all", "tags": ["contests", "prizes", "cruise", "competition"]}'),

-- 🎮 Gamification Features
('feature', 'Achievements', 'Earn badges and unlock features as you progress. Celebrate milestones and accomplishments in your relationship journey. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["gamification", "badges", "achievements", "rewards"]}'),
('feature', 'Points System', 'Earn gamification points for activities like sending love notes, completing goals, taking quizzes, and more. Points unlock features and achievements. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["gamification", "points", "rewards", "activities"]}'),
('feature', 'Premium Features', 'Unlock advanced features with progress. As you engage with the platform and earn points, unlock new capabilities and tools. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["gamification", "unlocks", "progression", "features"]}'),
('feature', 'Levels', 'Progress through relationship levels as you grow together. Each level unlocks new features and recognition. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["gamification", "levels", "progression", "growth"]}'),

-- 🌈 Inclusivity Features
('feature', 'LGBTQ+ Support', 'Specialized resources and content for LGBTQ+ couples. Inclusive features, expert advice, and community support tailored to LGBTQ+ relationships. Available in all tiers, with enhanced resources in Exclusive.', '{"language": "en", "subscription_tier": "all", "tags": ["inclusivity", "lgbtq", "support", "diversity"]}'),
('feature', 'Multi-Language Support', 'Platform available in 7 languages: English (EN), Spanish (ES), French (FR), Italian (IT), German (DE), Dutch (NL), Portuguese (PT). Chatbot responds in user''s preferred language.', '{"language": "en", "subscription_tier": "all", "tags": ["international", "languages", "accessibility"]}'),
('feature', 'Diversity Section', 'Celebrate all types of relationships. Inclusive content, resources, and community for couples of all backgrounds, orientations, and relationship types. Available in all tiers.', '{"language": "en", "subscription_tier": "all", "tags": ["inclusivity", "diversity", "celebration", "all-couples"]}');

-- Subscription Tier Information (Detailed)
INSERT INTO chatbot_knowledge (content_type, title, content, metadata) VALUES
('faq', 'Basis Subscription (FREE)', 'Basis tier includes: 50+ Love Notes Library, Basic Relationship Quizzes, Monthly Date Ideas (5 ideas), Anniversary Reminders, Digital Memory Timeline, Mobile App Access, Email Support. Perfect for couples just starting their journey.', '{"language": "en", "tags": ["subscription", "pricing", "free", "basis"]}'),
('faq', 'Premiere Subscription ($19.99/month) - MOST POPULAR', 'Premiere tier includes everything in Basis, plus: 1000+ Love Notes Library, AI Relationship Coach (50 questions/month), Unlimited Date Ideas with Filters, Relationship Goals Tracker, Advanced Quizzes & Compatibility Tests, Schedule Surprise Messages, Ad-Free Experience, Priority Support, Early Access to New Features. Best value for active couples.', '{"language": "en", "tags": ["subscription", "pricing", "premiere", "popular"]}'),
('faq', 'Exclusive Subscription ($34.99/month)', 'Exclusive tier includes everything in Premiere, plus: Unlimited Love Notes Library, Unlimited AI Relationship Coach, AI Content Creator (poems, letters), Personalized Relationship Reports, Exclusive Couples Community Access, Monthly Contest Entry for Prizes, LGBTQ+ Specialized Resources, 1-on-1 Expert Consultation (1/month), Premium WhatsApp Support, Exclusive Discounts on Lovers Store, VIP Badge & Recognition. For couples who want the full experience.', '{"language": "en", "tags": ["subscription", "pricing", "exclusive", "premium"]}'),
('faq', 'Subscription Comparison', 'Basis (FREE): Entry-level features for new couples. Premiere ($19.99/month) ⭐: Most popular, great balance of features and value. Exclusive ($34.99/month): Full access to all features, unlimited usage, premium support, and exclusive perks. Choose based on your relationship goals and engagement level.', '{"language": "en", "tags": ["subscription", "pricing", "comparison"]}'),
('faq', 'How to Send Love Notes', 'Go to Love Notes page, choose your note style, customize it, select delivery method (app, SMS, or social media), add personal touches, and send. You can also schedule notes for later.', '{"language": "en", "tags": ["love-notes", "how-to"]}'),
('faq', 'Creating Relationship Goals', 'Navigate to Relationship Goals, click Create Goal, choose a category (communication, intimacy, activities, etc.), set your goal and action steps, and track progress together.', '{"language": "en", "tags": ["goals", "how-to"]}'),
('faq', 'Finding Date Ideas', 'Visit Date Ideas page, use filters for budget, location, and occasion, browse curated suggestions, or create custom date ideas tailored to your preferences.', '{"language": "en", "tags": ["date-ideas", "how-to"]}');

-- Relationship Advice Tips
INSERT INTO chatbot_knowledge (content_type, title, content, metadata) VALUES
('advice', 'Improving Communication', 'Use "I" statements instead of "you" statements. Practice active listening. Take breaks when emotions are high. Schedule regular check-ins. Use Communication Practice feature to build skills.', '{"language": "en", "tags": ["communication", "tips"]}'),
('advice', 'Resolving Conflicts', 'Identify the root cause, not just the surface issue. Use conflict resolution frameworks. Practice empathy and understanding. Consider professional help for persistent issues. Use Communication Practice scenarios.', '{"language": "en", "tags": ["conflict", "resolution"]}'),
('advice', 'Reconnecting After a Fight', 'Take time to cool down. Apologize sincerely. Use Love Notes to express feelings. Practice Communication exercises together. Set a Relationship Goal to improve conflict resolution.', '{"language": "en", "tags": ["conflict", "reconnection"]}'),
('advice', 'Keeping the Spark Alive', 'Plan regular date nights using Date Ideas. Send surprise Love Notes. Try new activities together. Use Relationship Quizzes to discover new things about each other. Celebrate Milestones together.', '{"language": "en", "tags": ["connection", "romance"]}'),
('advice', 'Building Intimacy', 'Practice open communication. Use guided Meditation together. Share in Shared Journals. Set Relationship Goals around intimacy. Consider Counseling Support if needed.', '{"language": "en", "tags": ["intimacy", "connection"]}');

-- Note: In production, you would generate embeddings for these entries using the generateEmbedding function
-- For now, embeddings can be added later or generated via a script

